apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.distribute-enriched-event.triggered
      requests:
        - "curl --request POST --data '{  \"original_data\": {{ .data.tags
          }},  \"enriched_data\": {{ .data.enrich }}}'
          https://webhook.site/4d796d31-f4f6-4c13-a2e6-ef5cb58d2db6"
      subscriptionID: d90209c4-d1e5-4d15-8ee1-5a67d07627bb
